Transformation change datatype
gopaldivami/cdap-ui-forked pull request #282
Opened 2022-10-21 13:45 UTC by richadivami

# TITLE

## Description
Summary of changes

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [Jira issue #](fill-in.org)

## Test Plan

## Screenshots

2022-10-22 06:15 UTC, adityadivami requested changes
CR-1. Add Data Testids to the following items
a. onClick, onChange and any event triggering elements
b. All labels whether Typograpahy or not

CR-2. Use i18n wherever we have labels in the DOM and reuse same if required in the states, utils and services

CR-3. Variable names should be camelCase
CR-4. Each file should have copyrights text
CR-5. Any file can contain only 1 component
CR-6. Use export default function () {} for declaring any component
CR-7. Add proper null checks
CR-8. Add interfaces to states, props, variables, functions. Never use any as type.
CR-9. Spread props as component arguments, rather than using props directly

2022-10-22 07:53 UTC, adityadivami commented on app/cdap/components/GridTable/index.tsx
> +  const [rowsDataList, setRowsDataList] = useState([] as IRowData[]);
const [rowsDataList, setRowsDataList] = useState([] as IRowData[]);

should be 
const [rowsDataList, setRowsDataList] = useState<IRowData[]>([]);

2022-10-22 07:53 UTC, adityadivami commented on app/cdap/components/GridTable/index.tsx
> +  const [rowsDataList, setRowsDataList] = useState([] as IRowData[]);
Please make sure all types are given like this

2022-10-22 10:50 UTC, merged

2022-10-24 05:42 UTC, dlakshmi123 commented on app/cdap/components/AddTransformation/utils.ts
> +  if (DATATYPE_OPTIONS.some((item) => item.value === functionName)) {
null check

2022-10-24 05:43 UTC, dlakshmi123 commented on app/cdap/components/AddTransformation/index.tsx
> +    const directive = getDirective(functionName, selectedColumns[0].label);
add type for directive

2022-10-24 06:11 UTC, dlakshmi123 commented
CR-1. Add Data Testids to the following items
a. onClick, onChange and any event triggering elements
b. All labels whether Typograpahy or not
CR-2. Use i18n wherever we have labels in the DOM and reuse same if required in the states, utils and services
CR-3. Variable names should be camelCase
CR-4. Each file should have copyrights text
CR-5. Any file can contain only 1 component
CR-6. Use export default function () {} for declaring any component
CR-7. Add proper null checks
CR-8. Add interfaces to states, props, variables, functions. Never use any as type.
CR-9. Spread props as component arguments, rather than using props directly
CR-10: Remove commented code and console logs
CR-11: Make sure the branch has changes only specific to the feature or the task it is expected
CR-12: Use Typography wherever we have labels being displayed on the screen. Do not write text inside div or p tags directly.

//ignore for now
CR-13: Do not keep logic / data manipulation / API calls in the component file. Move logic / data manipulation to utils and API calls to services. Create folder for services and keep function name as the filename for each service.

2022-10-24 06:39 UTC, dlakshmi123 commented on app/cdap/components/GridTable/index.tsx
>  export default function GridTable() {
use anonymous function

2022-10-28 05:15 UTC, richadivami commented on app/cdap/components/AddTransformation/index.tsx
> +    const directive = getDirective(functionName, selectedColumns[0].label);
Done

2022-10-28 05:15 UTC, richadivami commented on app/cdap/components/AddTransformation/utils.ts
> +  if (DATATYPE_OPTIONS.some((item) => item.value === functionName)) {
Done

2022-10-28 05:16 UTC, richadivami commented on app/cdap/components/GridTable/index.tsx
>  export default function GridTable() {
Done